#!/bin/bash

# Change the current directory to "~/x"
cd ~/x

# Remove all files and folders in the current directory
rm -rf *

# Ask the user for input and assigns it to a variable "x"
read -p "Name: " x

# Downloads videos from the top 12 posts on a subreddit specified by the user input "x" using youtube-dl and curl
youtube-dl $(curl -H "User-agent: 'your bot 0.1'" https://www.reddit.com/r/$x/top.json\?limit\=12 | jq '.' | grep url_overridden_by_d)

# Create a new directory called "blur"
mkdir blur

# Apply a blur effect to all mp4 files in the current directory using ffmpeg
for f in *mp4; do ffmpeg -i $f -lavfi '[0:v]scale=ih*16/9:-1,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)' -y blur/$f; done

# Remove all original mp4 files
rm *.mp4

# Create a file called "file_list.txt" and list the blurred mp4 files in the "blur" directory
for f in blur/*mp4; do echo "file $f" >> file_list.txt ; done

# Concatenate the blurred mp4 files into a single file called "final.mp4" using ffmpeg
ffmpeg -f concat -i file_list.txt final.mp4

# Remove the "blur" directory and its contents
rm -rf blur
